apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fraud-detection-cluster
  region: eu-west-2
  version: "1.30"

managedNodeGroups:
  - name: spot-ng
    instanceTypes:
      - t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    spot: true
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
